# Generated by Django 5.1.5 on 2025-02-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Appointment", "0001_initial"),
        ("Doctor", "0001_initial"),
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="available_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="Doctor.availabletime",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="Doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="Patient.patient",
            ),
        ),
    ]
