# Generated by Django 5.1.5 on 2025-02-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Doctor", "0001_initial"),
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Patient.patient"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.ManyToManyField(to="Doctor.specialization"),
        ),
    ]
