# Generated by Django 5.1.5 on 2025-02-03 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabletime",
            name="day",
        ),
        migrations.AddField(
            model_name="availabletime",
            name="date",
            field=models.DateField(default=datetime.date(2025, 2, 3)),
            preserve_default=False,
        ),
    ]
