# Generated by Django 5.1.5 on 2025-02-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0003_remove_availabletime_day_availabletime_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="specialization",
            name="icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
