# Generated by Django 5.1.5 on 2025-02-13 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0004_designation_icon_specialization_icon"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="availabletime",
            unique_together={("doctor", "date", "start_time")},
        ),
    ]
