# Generated by Django 5.1.5 on 2025-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0005_alter_availabletime_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
