# Generated by Django 5.1.5 on 2025-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0006_alter_doctor_experience_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
