version: "3.9"

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A hospital_management worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  celery-beat:
    build: .
    command: celery -A hospital_management beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
