// src/constants/availableTimeConstants.js

// Fetch All Available Times
export const AVAILABLE_TIME_LIST_REQUEST = "AVAILABLE_TIME_LIST_REQUEST";
export const AVAILABLE_TIME_LIST_SUCCESS = "AVAILABLE_TIME_LIST_SUCCESS";
export const AVAILABLE_TIME_LIST_FAIL = "AVAILABLE_TIME_LIST_FAIL";

// Create New Available Time
export const AVAILABLE_TIME_CREATE_REQUEST = "AVAILABLE_TIME_CREATE_REQUEST";
export const AVAILABLE_TIME_CREATE_SUCCESS = "AVAILABLE_TIME_CREATE_SUCCESS";
export const AVAILABLE_TIME_CREATE_FAIL = "AVAILABLE_TIME_CREATE_FAIL";
export const AVAILABLE_TIME_CREATE_RESET = "AVAILABLE_TIME_CREATE_RESET";

// Update Available Time
export const AVAILABLE_TIME_UPDATE_REQUEST = "AVAILABLE_TIME_UPDATE_REQUEST";
export const AVAILABLE_TIME_UPDATE_SUCCESS = "AVAILABLE_TIME_UPDATE_SUCCESS";
export const AVAILABLE_TIME_UPDATE_FAIL = "AVAILABLE_TIME_UPDATE_FAIL";
export const AVAILABLE_TIME_UPDATE_RESET = "AVAILABLE_TIME_UPDATE_RESET";

// Delete Available Time
export const AVAILABLE_TIME_DELETE_REQUEST = "AVAILABLE_TIME_DELETE_REQUEST";
export const AVAILABLE_TIME_DELETE_SUCCESS = "AVAILABLE_TIME_DELETE_SUCCESS";
export const AVAILABLE_TIME_DELETE_FAIL = "AVAILABLE_TIME_DELETE_FAIL";
