export const DESIGNATION_LIST_REQUEST = "DESIGNATION_LIST_REQUEST";
export const DESIGNATION_LIST_SUCCESS = "DESIGNATION_LIST_SUCCESS";
export const DESIGNATION_LIST_FAIL = "DESIGNATION_LIST_FAIL";

export const SPECIALIZATION_LIST_REQUEST = "SPECIALIZATION_LIST_REQUEST";
export const SPECIALIZATION_LIST_SUCCESS = "SPECIALIZATION_LIST_SUCCESS";
export const SPECIALIZATION_LIST_FAIL = "SPECIALIZATION_LIST_FAIL";

export const DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST";
export const DOCTOR_LIST_SUCCESS = "DOCTOR_LIST_SUCCESS";
export const DOCTOR_LIST_FAIL = "DOCTOR_LIST_FAIL";

export const DOCTOR_PROFILE_REQUEST = "DOCTOR_PROFILE_REQUEST";
export const DOCTOR_PROFILE_SUCCESS = "DOCTOR_PROFILE_SUCCESS";
export const DOCTOR_PROFILE_FAIL = "DOCTOR_PROFILE_FAIL";
export const DOCTOR_PROFILE_UPDATE_REQUEST = "DOCTOR_PROFILE_UPDATE_REQUEST";
export const DOCTOR_PROFILE_UPDATE_SUCCESS = "DOCTOR_PROFILE_UPDATE_SUCCESS";
export const DOCTOR_PROFILE_UPDATE_FAIL = "DOCTOR_PROFILE_UPDATE_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";
