export const PATIENT_PROFILE_REQUEST = "PATIENT_PROFILE_REQUEST";
export const PATIENT_PROFILE_SUCCESS = "PATIENT_PROFILE_SUCCESS";
export const PATIENT_PROFILE_FAIL = "PATIENT_PROFILE_FAIL";

export const PATIENT_UPDATE_PROFILE_REQUEST = "PATIENT_UPDATE_PROFILE_REQUEST";
export const PATIENT_UPDATE_PROFILE_SUCCESS = "PATIENT_UPDATE_PROFILE_SUCCESS";
export const PATIENT_UPDATE_PROFILE_FAIL = "PATIENT_UPDATE_PROFILE_FAIL";
export const PATIENT_UPDATE_PROFILE_RESET = "PATIENT_UPDATE_PROFILE_RESET";
